import { describe, it, expect } from 'vitest';
import { generateFolderName, extractIgdbId, parseFolderName } from '../src/services/naming.js';

const DEFAULT_SCHEME = '<Game Name> - <Release Year> [<IGDB_ID>]';

describe('extractIgdbId', () => {
  it('recovers the id from a folder generated by the default scheme', () => {
    const folder = generateFolderName({ title: 'HELLDIVERS 2', releaseYear: 2024, igdbId: 250616 }, DEFAULT_SCHEME);
    expect(extractIgdbId(folder, DEFAULT_SCHEME)).toBe(250616);
  });

  it('recovers the id when the release year is omitted (collapsed spacing)', () => {
    const folder = generateFolderName({ title: 'HELLDIVERS 2', releaseYear: null, igdbId: 250616 }, DEFAULT_SCHEME);
    expect(extractIgdbId(folder, DEFAULT_SCHEME)).toBe(250616);
  });

  it('handles titles containing a hyphen', () => {
    const folder = generateFolderName({ title: 'Half-Life 2', releaseYear: 2004, igdbId: 42 }, DEFAULT_SCHEME);
    expect(extractIgdbId(folder, DEFAULT_SCHEME)).toBe(42);
  });

  it('works against a bracket-free custom scheme', () => {
    const scheme = '<Game Name> (<Release Year>) <IGDB_ID>';
    const folder = generateFolderName({ title: 'Portal', releaseYear: 2007, igdbId: 1234 }, scheme);
    expect(extractIgdbId(folder, scheme)).toBe(1234);
  });

  it('works against a scheme with no release year token', () => {
    const scheme = '<Game Name> [<IGDB_ID>]';
    const folder = generateFolderName({ title: 'Portal', releaseYear: 2007, igdbId: 1234 }, scheme);
    expect(extractIgdbId(folder, scheme)).toBe(1234);
  });

  it('returns null for a name that does not fit the scheme', () => {
    expect(extractIgdbId('just some random folder', DEFAULT_SCHEME)).toBeNull();
  });

  it('returns null for empty/garbage input', () => {
    expect(extractIgdbId('', DEFAULT_SCHEME)).toBeNull();
    expect(extractIgdbId('   ', DEFAULT_SCHEME)).toBeNull();
  });
});

describe('parseFolderName', () => {
  it('recovers the title and release year alongside the id', () => {
    const folder = 'Clair Obscur Expedition 33 - 2025 [305152]';
    expect(parseFolderName(folder, DEFAULT_SCHEME)).toEqual({
      title: 'Clair Obscur Expedition 33',
      releaseYear: 2025,
      igdbId: 305152,
    });
  });

  it('leaves releaseYear null when the folder was generated without one', () => {
    const folder = generateFolderName({ title: 'HELLDIVERS 2', releaseYear: null, igdbId: 250616 }, DEFAULT_SCHEME);
    expect(parseFolderName(folder, DEFAULT_SCHEME)).toEqual({
      title: 'HELLDIVERS 2',
      releaseYear: null,
      igdbId: 250616,
    });
  });
});
